This is a demo of reference table pages with CRUD actions : currencies, countries, cities and organizations.<br>
It is hosted on somee.com with ASP.NET 1.1 + Access. It also works with ASP.NET 2.0 and other databases.
It may seem a little slow and the session is often lost (you have to reconnect) but it's a free hosting (with advertisement).
On a standard PC, it works fine without slowness.<br>
<br>
All these pages are developed without a single line of code (no code behind, no aspx/ascx).
Here are the description files and few aspx pages which have served to develop this demonstration.
All the rest is produced by the framework.<br>
Get <a href="greco-demo-src.zip">demo sources</a>.<br>
Go to <a href="http://dactylo6.ifrance.com">projet presentation</a>.<br>
<br>
On each page you can get the module and resource files (menu link "Get description").
<br>
<li>Currencies : simple list / detail</li>
<li>Countries : list with search criteria / detail with sublist</li>
<li>Cities : list with search criteria / simple detail (view mode instead of edit mode)</li>
<li>Organizations : simple list / detail with sublist</li>
<li>Currencies 2 : list / detail with complex layout and sublist with special insert/delete (see [sql] section)</li>
