Il s'agit d'une gestion de tables de référentiel sur des
monnaies, pays, villes et organisations.<br>
L'hébergeur somee.com fournit ASP.NET 1.1 + une base Access. Cela marche aussi avec
ASP.NET 2.0 et d'autres bases de données.
L'appli peut paraître un peu lente mais c'est un hébergeur gratuit (avec pub).
Sur un PC standard, il n'y a pas de problème de lenteur.<br>
<br>
Tous ces écrans sont développés sans la moindre ligne de code spécifique (ni
code behind, ni code de présentation aspx / ascx).<br>
Voici les fichiers de description et les quelques pages aspx qui sont les
seuls à avoir servi à développer cette démonstration. Tous le reste est pris en
charge par le framework.<br>
Accès aux <a href="greco-demo-src.zip">sources de la démo</a>.<br>
Accès à la <a href="http://dactylo6.ifrance.com">présentation projet</a>.<br>
<br>
A chaque page vous pouvez voir via le lien "Accès au descripteur module / ressource" du menu les
fichiers module et ressource qui constituent l'unique "source" à développer de la page.
<br>
<li>Devises : liste / détail simple</li>
<li>Pays : liste avec critère de recherche / détail avec sous-liste</li>
<li>Villes : liste avec critère de recherche / détail simple (le détail se positionne par défaut en mode view)</li>
<li>Organisations : liste simple / détail avec sous-liste</li>
<li>Devises 2 : liste / détail avec affichage plus complexe en 2 colonnes et sous-liste qui effectue des
                insert/delete simulés en base par un update</li>
